version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ⬆
  # Python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ⬆
    groups:
      main-dependencies:
        dependency-type: "production"
      dev-dependencies:
        dependency-type: "development"
        exclude-patterns:
          - "mkdocs*"
      docs-dependencies:
        patterns:
          - "mkdocs*"
