# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
        args: ["--unsafe"]
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        args:
          - --py310-plus

  - repo: local
    hooks:
      - id: ruff-format
        name: ruff-format
        entry: make format
        types: [python]
        language: system
        pass_filenames: false
      - id: ruff-lint
        name: ruff-lint
        entry: make lint
        types: [python]
        language: system
        pass_filenames: false
      - id: mypy
        name: mypy
        entry: make typecheck
        types: [python]
        language: system
        pass_filenames: false
