# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-added-large-files
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev:  v0.0.277
    hooks:
    -   id: ruff
        args:
        - --fix

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    -   id: pyupgrade
        args:
        - --py310-plus

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
    -   id: mypy
        args: [--strict, --ignore-missing-imports]
        additional_dependencies:
            - textual==0.30.0
            - textual-dev==1.0.1
            - httpx==0.24.1
            - pydantic==2.1
            - pytest==7.4.0
            - pytest-asyncio==0.21.0
