# Site config
site_name: Pub Analyzer

site_author: Alejandro Gaspar
site_description: Pub Analyzer is a text user interface (TUI), written in python, which automates the generation of scientific production reports using OpenAlex

repo_url: https://github.com/alejandrgaspar/pub-analyzer
site_url: https://pub-analyzer.com/

copyright: Copyright &copy; Alejandro Gaspar.

watch:
  - pub_analyzer

# Theme config
theme:
  name: material
  custom_dir: docs/overrides
  icon:
    logo: fontawesome/solid/book
    admonition:
      example: simple/python
  palette:
    primary: pink
    accent: pink
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.footer
    - navigation.indexes
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - toc.follow

markdown_extensions:
  - admonition:
  - attr_list
  - codehilite
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: textual
          class: textual
          format: !!python/name:textual._doc.format_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

extra_css:
  - assets/css/custom.css

# Plugins
plugins:
  search:
  autorefs:
  mkdocstrings:
    custom_templates: docs/_templates
    handlers:
      python:
        options:
          docstring_style: google
          show_root_toc_entry: false
          separate_signature: true

# Social links
extra:
  social:
    - icon: material/web
      link: https://gaspar.land/
      name: Author web page
    - icon: fontawesome/brands/github
      link: https://github.com/alejandrgaspar/pub-analyzer
      name: Pub Analyzer on github
    - icon: simple/python
      link: https://pypi.org/project/pub-analyzer/
      name: Pub Analyzer on pypi

# Nav paths
nav:
  - Introduction:
    - "index.md"
    - "getting_started.md"
    - "acknowledgement.md"
    - "help.md"
  - User Guide:
    - "user/index.md"
  - Dev Guide:
    - "dev/index.md"
  - API:
    - Internal:
      - "api/internal/identifier.md"
      - "api/internal/render.md"
      - "api/internal/report.md"
    - Models:
      - "api/models/author.md"
      - "api/models/institution.md"
      - "api/models/report.md"
      - "api/models/source.md"
      - "api/models/work.md"
  - Roadmap:
    - roadmap/index.md
  - Author's website: https://gaspar.land
