"""Aggregation of works into report summaries."""

from collections.abc import Iterable, Sequence
from typing import NamedTuple

from pub_analyzer.internal import identifier
from pub_analyzer.models.report import (
    CitationReport,
    CitationSummary,
    CitationType,
    OpenAccessSummary,
    SourcesSummary,
    WorkReport,
    WorkTypeCounter,
)
from pub_analyzer.models.source import DehydratedSource, Source
from pub_analyzer.models.work import Authorship, Work


class YearCount(NamedTuple):
    """Works published and citations received in a year.

    Entity agnostic: the builder converts these into the year count Model matching
    the entity the report belongs to.
    """

    year: int
    works_count: int
    cited_by_count: int


def get_authors_list(authorships: list[Authorship]) -> list[str]:
    """Collect OpenAlex IDs from authors in a list of authorship's.

    Args:
        authorships: List of authorships.

    Returns:
        Authors keys IDs.
    """
    return [identifier.get_author_id(authorship.author) for authorship in authorships]


def get_citation_type(original_work_authors: list[str], cited_work_authors: list[str]) -> CitationType:
    """Compare two lists of authors and returns the citation type.

    Based on the authors of a given work and the authors of another work that cites the analyzed work,
    calculate the citation type.

    Args:
        original_work_authors: List of the authors of the evaluated work.
        cited_work_authors: List of the authors of the citing document.

    Returns:
        Calculated cite type (Type A or Type B).

    Info:
        **Type A:** Citations made by researchers in documents where the evaluated author or
        one of his co-authors does not appear as part of the authorship of the citing documents.

        **Type B:** Citations generated by the author or one of the co-authors of the work being
        analyzed.
    """
    original_set = set(original_work_authors)
    cited_set = set(cited_work_authors)

    return CitationType.TypeA if not original_set.intersection(cited_set) else CitationType.TypeB


def build_work_report(work: Work, citing_works: Iterable[Work]) -> WorkReport:
    """Classify every citation a work received and summarize them.

    Args:
        work: The work being evaluated.
        citing_works: Works that cite the evaluated work.

    Returns:
        Work report with each citation classified and counted.
    """
    work_authors = get_authors_list(authorships=work.authorships)

    cited_by: list[CitationReport] = []
    citation_summary = CitationSummary()

    for citing_work in citing_works:
        citing_authors = get_authors_list(authorships=citing_work.authorships)
        citation_type = get_citation_type(work_authors, citing_authors)

        citation_summary.add_cite_type(citation_type)
        cited_by.append(CitationReport(work=citing_work, citation_type=citation_type))

    return WorkReport(work=work, cited_by=cited_by, citation_summary=citation_summary)


def summarize_citations(work_reports: Iterable[WorkReport]) -> CitationSummary:
    """Total the citation counts of every work in the report.

    Args:
        work_reports: Reports of each evaluated work.

    Returns:
        Citation summary across all works.
    """
    summary = CitationSummary()
    for work_report in work_reports:
        summary.type_a_count += work_report.citation_summary.type_a_count
        summary.type_b_count += work_report.citation_summary.type_b_count

    return summary


def summarize_open_access(works: Iterable[Work]) -> OpenAccessSummary:
    """Count the Open Access status of every work.

    Args:
        works: Works to count.

    Returns:
        Open Access summary.
    """
    summary = OpenAccessSummary()
    for work in works:
        summary.add_oa_type(work.open_access.oa_status)

    return summary


def summarize_work_types(works: Iterable[Work]) -> list[WorkTypeCounter]:
    """Count how many works of each type the report holds.

    Args:
        works: Works to count.

    Returns:
        One counter per work type, in order of first appearance.
    """
    counts: dict[str, int] = {}
    for work in works:
        counts[work.type] = counts.get(work.type, 0) + 1

    return [WorkTypeCounter(type_name=type_name, count=count) for type_name, count in counts.items()]


def count_by_year(work_reports: Sequence[WorkReport]) -> list[YearCount]:
    """Count works published and citations received, per year.

    A work counts towards its own publication year, and a citation counts towards the
    publication year of the citing work. Works without a publication year are skipped.

    Args:
        work_reports: Reports of each evaluated work.

    Returns:
        Year counts, sorted by year.
    """
    works_count: dict[int, int] = {}
    cited_by_count: dict[int, int] = {}

    for work_report in work_reports:
        if work_report.work.publication_year:
            works_count[work_report.work.publication_year] = works_count.get(work_report.work.publication_year, 0) + 1

        for citation in work_report.cited_by:
            if citation.work.publication_year:
                cited_by_count[citation.work.publication_year] = cited_by_count.get(citation.work.publication_year, 0) + 1

    return [
        YearCount(year=year, works_count=works_count.get(year, 0), cited_by_count=cited_by_count.get(year, 0))
        for year in sorted(works_count.keys() | cited_by_count.keys())
    ]


def collect_dehydrated_sources(works: Iterable[Work]) -> list[DehydratedSource]:
    """Collect every distinct source hosting a location of the given works.

    Args:
        works: Works whose locations are inspected.

    Returns:
        Distinct sources, in order of first appearance.
    """
    sources: dict[str, DehydratedSource] = {}
    for work in works:
        for location in work.locations:
            if location.source:
                sources.setdefault(str(location.source.id), location.source)

    return list(sources.values())


def build_sources_summary(sources: Iterable[Source]) -> SourcesSummary:
    """Sort sources by impact.

    Args:
        sources: Sources to summarize.

    Returns:
        Sources summary, sorted by 2-year mean citedness, descending.
    """
    sources_sorted = sorted(sources, key=lambda source: source.summary_stats.two_yr_mean_citedness, reverse=True)

    return SourcesSummary(sources=sources_sorted)
