"""
Factories to build Model instances in tests.

These let a test state only the fields it cares about, instead of carrying a full
OpenAlex payload around. Use them for logic tests.
"""

from typing import Any

from pub_analyzer.models.author import DehydratedAuthor
from pub_analyzer.models.source import DehydratedSource
from pub_analyzer.models.work import Authorship, Location, OpenAccessStatus, Work

_WORK_COUNTER = iter(range(1, 1_000_000))


def make_author(author_id: str, display_name: str | None = None) -> DehydratedAuthor:
    """Build a DehydratedAuthor from a bare OpenAlex key.

    Args:
        author_id: OpenAlex key, e.g. `"A123"`.
        display_name: Optional display name.

    Returns:
        DehydratedAuthor instance.
    """
    return DehydratedAuthor(id=f"https://openalex.org/{author_id}", display_name=display_name)  # type: ignore[arg-type]


def make_source(source_id: str, display_name: str = "Source") -> DehydratedSource:
    """Build a DehydratedSource from a bare OpenAlex key.

    Args:
        source_id: OpenAlex key, e.g. `"S123"`.
        display_name: Optional display name.

    Returns:
        DehydratedSource instance.
    """
    return DehydratedSource(
        id=f"https://openalex.org/{source_id}",  # type: ignore[arg-type]
        display_name=display_name,
        issn_l=None,
        issn=None,
        is_oa=False,
        is_in_doaj=False,
        host_organization=None,
        type="journal",
    )


def make_location(source: DehydratedSource | None = None) -> Location:
    """Build a Location, optionally carrying a source.

    Args:
        source: Source hosting this location.

    Returns:
        Location instance.
    """
    return Location(
        is_oa=False,
        landing_page_url="https://example.org/work",
        license=None,
        pdf_url=None,
        version=None,
        source=source,
    )


def make_work(
    work_id: str | None = None,
    *,
    authors: list[str] | None = None,
    publication_year: int | None = 2020,
    work_type: str = "article",
    oa_status: OpenAccessStatus = OpenAccessStatus.closed,
    cited_by_count: int = 0,
    sources: list[str] | None = None,
    title: str = "Title",
    **overrides: Any,
) -> Work:
    """Build a Work with only the fields a test cares about.

    Args:
        work_id: OpenAlex key. Autogenerated and unique when omitted.
        authors: OpenAlex author keys to place in the authorship's.
        publication_year: Year of publication.
        work_type: Work type, as counted by works type summary.
        oa_status: Open Access status, as counted by the Open Access summary.
        cited_by_count: Citation count as reported by OpenAlex.
        sources: OpenAlex source keys, one location built per key.
        title: Work title.
        overrides: Any other Work field, passed through verbatim.

    Returns:
        Work instance.
    """
    work_id = work_id if work_id is not None else f"W{next(_WORK_COUNTER)}"
    url = f"https://openalex.org/{work_id}"

    fields: dict[str, Any] = {
        "id": url,
        "ids": {"openalex": url},
        "title": title,
        "publication_year": publication_year,
        "type": work_type,
        "open_access": {"is_oa": oa_status is not OpenAccessStatus.closed, "oa_status": oa_status},
        # Dumped to dicts because Work's `mode="before"` validators index into raw payloads.
        "authorships": [
            Authorship(author_position="first", author=make_author(author)).model_dump(mode="json")
            for author in (authors if authors is not None else [])
        ],
        "locations": [make_location(make_source(source)).model_dump(mode="json") for source in (sources if sources is not None else [])],
        "cited_by_count": cited_by_count,
        "awards": [],
        "keywords": [],
        "concepts": [],
        "topics": [],
        "referenced_works": [],
    }
    fields.update(overrides)

    return Work(**fields)
